language: android
jdk: oraclejdk8
notifications:
  email: false
sudo: false
git:
  submodules: false
android:
  components:
  - tools
  - build-tools-26.0.2
  - android-26
  - extra-android-m2repository
  - extra-android-support
before_install:
- chmod +x gradlew
- gem install fir-cli
before_cache:
- rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
- rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
  - "$HOME/.gradle/caches/"
  - "$HOME/.gradle/wrapper/"
script:
- "./gradlew assembleRelease"
before_deploy:
- ls app/build/outputs/apk/release/
#- mv app/build/outputs/apk/release/app-release-unsigned.apk  app/build/outputs/apk/release/lermaobs.apk
#- ls app/build/outputs/apk/release/
deploy:
  provider: releases
  on:
      repo: LerMao/lermao-Android
      tags: true
      all_branches: true
  api_key:
    secure: BEn5aL4MVykDc0jSYUprMRziEDOdb0OWXJQksDhJ7KYCVUVraXcjecUbFdfJ0k/MnqrdHoa9aPthB/WjobVh6u8VuHfGd9+mXD/bpLZX8iUCkJ9mS250KE7HBDuM5+s2NCNLiI7pVXDx+gSuGrXgVJOO+V7gharSeei3TzTbVsczO6vTFJpjwbcte7ZHctd1Pm9UplgkhTDwk5EzCZqOoFee0WX04VkTASXe0F0uDfRaxU8+dBS/GL/SLYqEpnXF9lCQGIhdlM8hhxrMAksPTpuRvdmNxF1RU7RgyhGWCbGV1cilfoWpHXG2anEtfaGxEE3UXpaHiJgiqSFq/AgvBx/PGy8y5j3vqlIfKP3kOwIOFmOE9FwmLyB04UvekAZMbyqSd4ADr51HNonFbR3sYQ/q5bG3AUQj8mhyU1QebKlvyoz1WleFPfAiIFKC48/f1uPNQlrm0/tJz+u1+G2Umgp+g5TNdKdWH0ZxZx07D/wOfA5BC20xssf2DTgc4eu8gTzgCvmFmpEXchF0wur00/suwWZ551lUqkO5BQl0FNu8JP3VgtUStbgwe6tNNgIWUYFhRBx1S5VOkpfWLQdpKoJ2cHYm/GVqk/Lp1huRr2ph3DTc2Gtq4fdFR0MGy1j0p5FyjUd9V5QRftNC3ZwugfvW0lwYXQ83QqkVa81ey4g=
  file: app/build/outputs/apk/release/app-release-unsigned.apk



after_success:
- fir login 3b7dbeac6e6d90f8615df748b44c975a
- fir me
- fir p app/build/outputs/apk/release/app-release-unsigned.apk
